fixtures:
  repositories:
    stdlib:
      repo: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '4.3.2'
    inifile:
      repo: 'https://github.com/puppetlabs/puppetlabs-inifile.git'
      ref: '1.3.0'
    chocolatey:
      repo: 'https://github.com/chocolatey/puppet-chocolatey.git'
      ref: '1.2.0'
  symlinks:
    splunkforwarder: "#{source_dir}"
