fixtures:
  repositories:
    stdlib:
      repo: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '4.3.2'
    inifile:
      repo: 'https://github.com/puppetlabs/puppetlabs-inifile.git'
      ref: '1.3.0'
    concat:
      repo: 'https://github.com/puppetlabs/puppetlabs-concat.git'
      ref: '1.2.4'
    chocolatey:
      repo: 'https://github.com/chocolatey/puppet-chocolatey.git'
      ref: '1.2.0'
    archive:
      repo: 'https://github.com/voxpupuli/puppet-archive.git'
      ref: '0.4.4'
  symlinks:
    splunkforwarder: "#{source_dir}"
