language: ruby
bundler_args: --without development system_tests
before_install: rm Gemfile.lock || true
script: bundle exec rake test
sudo: false
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0

env:
  - PUPPET_VERSION="~> 3.4.0"
  - PUPPET_VERSION="~> 3.5.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 3.6.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 3.7.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 3.7.0" STRICT_VARIABLES=yes FUTURE_PARSER=yes
  - PUPPET_VERSION="~> 4.0.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 4.1.0"
  - PUPPET_VERSION="~> 4.2.0"
  - PUPPET_VERSION="~> 4.3.0"

matrix:
  exclude:
  - rvm: 1.9.3
    env: PUPPET_VERSION="~> 4.0.0"
  - rvm: 1.9.3
    env: PUPPET_VERSION="~> 4.1.0"
  - rvm: 1.9.3
    env: PUPPET_VERSION="~> 4.2.0"
  - rvm: 1.9.3
    env: PUPPET_VERSION="~> 4.3.0"
  - rvm: 2.0.0
    env: PUPPET_VERSION="~> 4.0.0"
  - rvm: 2.0.0
    env: PUPPET_VERSION="~> 4.1.0"
  - rvm: 2.0.0
    env: PUPPET_VERSION="~> 4.2.0"
  - rvm: 2.0.0
    env: PUPPET_VERSION="~> 4.3.0"
  - rvm: 2.1.0
    env: PUPPET_VERSION="~> 3.4.0"

notifications:
  slack:
    secure: fw5MTlCm8tMU7UhegXS+DM8eyGQ3Rjs686RetsIs9JDLBT51gNgcn9xogfrDLd1cOxQkNSA6T6sI/KGrrrIVoGIfaJ/dJb1MpYUXEWiVSsC2OMn4gZogs4yMJL1R5abcYCEDbE5mjIXru6CbUsQfDfjJWBy1yAPbVVpMViBHhPcU8+RrybijnMOo+x4DvlmrOy4A9Fws08gKMJeK8GFJ9Sm4x4Au5tSL55XrAntMIb1+Q9etLAfSXcVryRi9tlg6cYOm0PzfvKzyEwVLgqWT3Q7q5efYjFWXuLIEhAPphWVNXWZMc1xurSHYOTfvHEy25MM3Eajrm4Nzurw6kmbMbyv68rqmF/dRJ7a6fJiMEQUOlux8ztCRbz2P/ijbq23/wbWDZ7f53RLpMJyQ2Q0hS46WEvqsJZgvvz8NYjPmHmcyZhMMP8m6K9bpJjlFXT7fK8GGCVDcX20mwO2NCL47WzJBjXDPU9X1CGFoByML8WOUirMzWV1dribB83wxknB6BIr5Bv/ws+wVfnApzItzbx4kEjbzIVjP50btFGdn6LmlU19K68IXNde1xWgTX/uMbR1S+k4ZP+Phfihq0TZDAEh2xj8K6c3cVNpAYFWZQAVLZB3Ftnzm/d9Ikzwr4OkjGltiHRCG8tuq/VgO+PVfxqpvekSHW8Aq/4RC6hiK0qg=
